### PR TITLE
Fix/update starter kit

### PR DESCRIPTION
**Pull request by Bluesmile82**
This PR updates the starter kit:

- Updates Rails to version 5.2 and other dependencies
- Updates package json, env, readme, base styles, settings
- Updates Footer, header, nav, sections and root

image

### CODE REVIEW

**Review by agnessa — DISMISSED** [review]
(removed obsolete review)

**Comment by aabdaab** [comment]
@agnessa `rails s` gives me errors, have you tried starting the project?

**Comment by agnessa** [comment]
you're right, sorry 😱

**Comment by agnessa** [comment]
AdminUser model was missing

**Pull request merged**
